sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 8888.216
  alioss:
    bucket-name: sky-fire-itcast
    endpoint: oss-cn-guangzhou.aliyuncs.com
    access-key-secret: a9Iwh9oS3crMmRoND4L1HMRZrqz0Z3
    access-key-id: LTAI5tSBSPcZ5sqftNiVkZts
  redis:
    host: localhost
    port: 6379
    password: 8888.216
    database: 10